# Generated by Django 5.0.4 on 2024-04-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon_url', models.URLField()),
                ('type', models.CharField(choices=[('exam', 'ЕГЭ'), ('olymp', 'Олимпиада')], max_length=10)),
            ],
        ),
    ]
